apiVersion: v1
Kind: Pod
metadata:
  name: config-pod
spec:
  containers:
    - name: nginx
      image: nginx
      env:
        - name: course
          valueFrom:
            configMapKeyRef:
              name: course-config
              key: course
        - name: duration
          valueFrom:
            configMapKeyRef:
              name: course-config
              key: duration
        - name: author
          valueFrom:
            configMapKeyRef:
              name: course-config
              key: author