apiVersion: v1
kind: Pod
metadata:
  name: config-pod
spec:
  containers:
    - name: nginx
      image: nginx
      env:
        - name: course
          valueFrom:
            configMapKeyRef:
              name: courseconfig
              key: course
        - name: duration
          valueFrom:
            configMapKeyRef:
              name: courseconfig
              key: duration
        - name: author
          valueFrom:
            configMapKeyRef:
              name: courseconfig
              key: author