apiVersion: v1
kind: Pod
metadata:
  name: kiran
  lables:
    name: ibm
    project: roboshop
    author: kiran
spec:
  containers:
  - image: tomcat
    name: tomcat
    resources:
      requests:
        cpu: "150m"
        memory: "200Mi"
      limits:
        cpu: "300m"
        memory: "350Mi"