apiVersion: v1
kind: Pod
metadata:
  name: probe
spec:
  containers:
  - image: nginx
    name: radilive
    livenessProbe:
      httpGet:
        path: /path
        port: 80
      initialDelaySeconds: 3
      periodSeconds: 5