apiVersion: v1
kind: Pod
metadata:
  name: secret-pod
spec:
  containers:
  - name: tomcat
    image: tomcat
    imagePullPolicy: Always
    env:
      - name: username
        valueFrom:
          secretKeyRef:
            name: my-secret
            key: username
      - name: password
        valueFrom:
          secretKeyRef:
            name: my-secret
            key: password

