apiVersion: v1
kind: Pod
metadata:
  name: with-node-affinity
spec:
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
          matchExpressions:
          - key: tier
            operator: In
            values:
            - frontend
      - weight: 80
        preference:
          matchExpressions:
          - key: tier
            operator: In
            values:
            - application
      
  containers:
  - name: httpd
    image: httpd