apiVersion: v1
kind: Secret
metadata:
  name: secret-config
type: Opaque
data:
    username: a2lyYW4=
    password: 2lyYW5rdW1hcjEyMw==


#  thse username is encode with base 64 in linux ec2 instance give
#echo -n kiran |base64you get some a2lyYW4= like this
#echo -n kirankumar123 |base64 youw ill get again something like 2ljuyrfckuhwljdhf
