apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::505159336758:role/eksctl-spot-cluster-nodegroup-spo-NodeInstanceRole-1DOZOS64U3A0Z
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
   userarn: arn:aws:iam::505159336758:user/roboshop
   username: roboshop
   userarn: arn:aws:iam::505159336758:user/ramesh
   username: ramesh
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"mapRoles":"- groups:\n  - system:bootstrappers\n  - system:nodes\n  rolearn: arn:aws:iam::505159336758:role/eksctl-spot-cluster-nodegroup-spo-NodeInstanceRole-1DOZOS64U3A0Z\n  username: system:node:{{EC2PrivateDNSName}}\n","mapUsers":"userarn: arn:aws:iam::505159336758:user/roboshop\nusername: roboshop\n"},"kind":"ConfigMap","metadata":{"annotations":{},"creationTimestamp":"2023-07-31T06:22:29Z","name":"aws-auth","namespace":"kube-system","resourceVersion":"1217","uid":"e54aebd2-ea51-45ca-bee3-37f290676c4f"}}
  creationTimestamp: "2023-07-31T12:00:26Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "51177"
  uid: efbeebfc-032a-42d1-b93e-acadb64dcbee
