apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  nginx.conf: |
#this config is loading from nginxconfig.map
  user nginx;
  worker_processes  1;
  events {
    worker_connections  10240;
  }
  http {
    server {
        listen       80;
        server_name  localhost;
        location / {
          root   html;
          index  index.html index.htm;
      }
    }
  }
---
apiVersion: v1
kind: Pod
metadata:
  name: web
  labels:
    container-name: web
    container-tier: frontend
spec:
  containers:
    - name: web
      imagePullPolicy: Always
      image: kiranprav/web:k1
      resources:
        requests:
          cpu: "150m"
          memory: "200Mi"
        limits:
          cpu: "300m"
          memory: "350Mi"
      ports:
        - containerPort: 80
      volumeMounts:
      - name: nginx-conf
        mountPath: /etc/nginx/nginx.conf
        subPath: nginx.conf
        readOnly: true  
  volumes:
  - name: nginx-conf
        configMap:
          name: nginx-conf
          items:
            - key: nginx.conf
              path: nginx.conf




 