---
# storageclasssyntax
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-sc
provisioner: ebs.csi.aws.com
reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
parameters:
  type: g2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-ebs-Dpvc
spec:
  storageClassName: ebs-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 34Gi  # Set the desired storage size
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - name: my-ebs-pv
          mountPath: /usr/share/nginx/html  # Mount path inside the container
  volumes:
    - name: my-ebs-pv
      persistentVolumeClaim:
        claimName: my-ebs-Dpvc

